version: '3.4'

services:
  userdb:
     container_name: userdb
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment: 
        MYSQL_ROOT_PASSWORD: admin1234
     ports: 
       - "3306:3306"
     volumes:
       - "./.mysql-data/db:/var/lib/mysql"

  usercache:
     container_name: usercache
     restart: always
     ports:
       - "6379:6379"

  userservice:
     container_name: userservice
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "ConnectionString=Server=userdb; port=3306; database=userInfo; user=root; password=admin1234; Persist Security Info=False; Connect Timeout=300"
       - "RedisConnectionString=usercache:6379"
     depends_on:
       - userdb
     ports:
       - "8000:80"
