version: '3.4'

services:
  userdb:
    image: mysql

  usercache:
    image: redis:alpine

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile

volumes:
  mysql_data: